config/routes.rb
Rails.application.routes.draw do
    resources :cocktails, only: [:index, :show, :new, :create]
    root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :description, :cocktail, :ingredient, presence: :true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]

  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end
end

def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
  end

  def destroy
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_cocktail_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/300/200?random');">
  <div class="card-description">
    <h2><%= cocktail.name %></h2>
  </div>
  <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
</div>

app/views/cocktails/index.html.erb
<h1 class="text-center">Your Cocktails</h1>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <%= render "cocktail_card", cocktail: cocktail %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<h1 class="text-center">New Cocktail</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>


<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Show Cocktails</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>